apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: monitoring
  labels:
    release: monitoring1  
spec:
  selector:
    matchLabels:
      app: api             
  namespaceSelector:
    matchNames:
      - three-tier
  endpoints:
    - port: http          
      path: /api/tasks/metrics      
      interval: 15s
